#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 {8192|16384|32768}"
  exit 1
fi

SEQ_LEN="$1"

case "$SEQ_LEN" in
  8192)
    RUN_ID="${RUN_ID:-baseline_1xh100_600s_seq8192}"
    TRAIN_BATCH_TOKENS=393216
    MUON_MOMENTUM_WARMUP_STEPS=190
    WARMDOWN_ITERS=381
    SEED_DEFAULT=1337
    ;;
  16384)
    RUN_ID="${RUN_ID:-baseline_1xh100_600s_seq16384}"
    TRAIN_BATCH_TOKENS=393216
    MUON_MOMENTUM_WARMUP_STEPS=118
    WARMDOWN_ITERS=236
    SEED_DEFAULT=1338
    ;;
  32768)
    RUN_ID="${RUN_ID:-baseline_1xh100_600s_seq32768}"
    TRAIN_BATCH_TOKENS=524288
    MUON_MOMENTUM_WARMUP_STEPS=50
    WARMDOWN_ITERS=100
    SEED_DEFAULT=1339
    ;;
  *)
    echo "Unsupported sequence length: $SEQ_LEN"
    echo "Expected one of: 8192, 16384, 32768"
    exit 1
    ;;
esac

export DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}"
export VOCAB_SIZE="${VOCAB_SIZE:-1024}"
export MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-600}"
export TRAIN_SEQ_LEN="$SEQ_LEN"
export TRAIN_BATCH_TOKENS
export TIED_EMBED_LR="${TIED_EMBED_LR:-0.030}"
export MATRIX_LR="${MATRIX_LR:-0.020}"
export SCALAR_LR="${SCALAR_LR:-0.020}"
export MUON_MOMENTUM="${MUON_MOMENTUM:-0.99}"
export MUON_MOMENTUM_WARMUP_START="${MUON_MOMENTUM_WARMUP_START:-0.92}"
export MUON_MOMENTUM_WARMUP_STEPS
export WARMDOWN_ITERS
export SEED="${SEED:-$SEED_DEFAULT}"
export WARMUP_STEPS="${WARMUP_STEPS:-20}"
export TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-10}"
export VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-50}"
export RUN_ID

echo "Running baseline with:"
echo "  RUN_ID=$RUN_ID"
echo "  TRAIN_SEQ_LEN=$TRAIN_SEQ_LEN"
echo "  TRAIN_BATCH_TOKENS=$TRAIN_BATCH_TOKENS"
echo "  TIED_EMBED_LR=$TIED_EMBED_LR"
echo "  MATRIX_LR=$MATRIX_LR"
echo "  SCALAR_LR=$SCALAR_LR"
echo "  MUON_MOMENTUM=$MUON_MOMENTUM"
echo "  MUON_MOMENTUM_WARMUP_START=$MUON_MOMENTUM_WARMUP_START"
echo "  MUON_MOMENTUM_WARMUP_STEPS=$MUON_MOMENTUM_WARMUP_STEPS"
echo "  WARMDOWN_ITERS=$WARMDOWN_ITERS"
echo "  WARMUP_STEPS=$WARMUP_STEPS"
echo "  SEED=$SEED"
echo "  MAX_WALLCLOCK_SECONDS=$MAX_WALLCLOCK_SECONDS"

torchrun --standalone --nproc_per_node=1 train_gpt.py
